# From https://github.com/gakonst/foundry-rust-template/
name: Solidity
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Pull library deps
        working-directory: contracts
        run: forge update

      - name: Run forge tests
        working-directory: contracts
        run: forge test

  bindings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Pull library deps
        working-directory: contracts
        run: forge update

      - name: Build contracts before checking bindings are correct
        working-directory: contracts
        run: forge build

      - name: Check bindings are correct
        run: forge bind --bindings-path ./bindings --root ./contracts --crate-name bindings

    # TODO: Add lints once forge fmt is in
